
# constraints
# ad9361

set_property IOSTANDARD LVDS [get_ports rx_clk_in_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports rx_clk_in_p]
set_property PACKAGE_PIN F17 [get_ports rx_clk_in_p]
set_property PACKAGE_PIN F16 [get_ports rx_clk_in_n]
set_property IOSTANDARD LVDS [get_ports rx_clk_in_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports rx_clk_in_n]
set_property IOSTANDARD LVDS [get_ports rx_frame_in_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports rx_frame_in_p]
set_property PACKAGE_PIN H18 [get_ports rx_frame_in_p]
set_property PACKAGE_PIN H17 [get_ports rx_frame_in_n]
set_property IOSTANDARD LVDS [get_ports rx_frame_in_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports rx_frame_in_n]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_p[0]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {rx_data_in_p[0]}]
set_property PACKAGE_PIN L20 [get_ports {rx_data_in_p[0]}]
set_property PACKAGE_PIN K20 [get_ports {rx_data_in_n[0]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_n[0]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {rx_data_in_n[0]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_p[1]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {rx_data_in_p[1]}]
set_property PACKAGE_PIN K19 [get_ports {rx_data_in_p[1]}]
set_property PACKAGE_PIN K18 [get_ports {rx_data_in_n[1]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_n[1]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {rx_data_in_n[1]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_p[2]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {rx_data_in_p[2]}]
set_property PACKAGE_PIN L17 [get_ports {rx_data_in_p[2]}]
set_property PACKAGE_PIN L16 [get_ports {rx_data_in_n[2]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_n[2]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {rx_data_in_n[2]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_p[3]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {rx_data_in_p[3]}]
set_property PACKAGE_PIN K17 [get_ports {rx_data_in_p[3]}]
set_property PACKAGE_PIN J17 [get_ports {rx_data_in_n[3]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_n[3]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {rx_data_in_n[3]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_p[4]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {rx_data_in_p[4]}]
set_property PACKAGE_PIN H19 [get_ports {rx_data_in_p[4]}]
set_property PACKAGE_PIN G19 [get_ports {rx_data_in_n[4]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_n[4]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {rx_data_in_n[4]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_p[5]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {rx_data_in_p[5]}]
set_property PACKAGE_PIN J16 [get_ports {rx_data_in_p[5]}]
set_property PACKAGE_PIN J15 [get_ports {rx_data_in_n[5]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_n[5]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {rx_data_in_n[5]}]

set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVDS} [get_ports tx_clk_out_p]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVDS} [get_ports tx_clk_out_n]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVDS} [get_ports tx_frame_out_p]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVDS} [get_ports tx_frame_out_n]
set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVDS} [get_ports {tx_data_out_p[0]}]
set_property -dict {PACKAGE_PIN A12 IOSTANDARD LVDS} [get_ports {tx_data_out_n[0]}]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVDS} [get_ports {tx_data_out_p[1]}]
set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVDS} [get_ports {tx_data_out_n[1]}]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVDS} [get_ports {tx_data_out_p[2]}]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVDS} [get_ports {tx_data_out_n[2]}]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVDS} [get_ports {tx_data_out_p[3]}]
set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVDS} [get_ports {tx_data_out_n[3]}]
set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVDS} [get_ports {tx_data_out_p[4]}]
set_property -dict {PACKAGE_PIN C12 IOSTANDARD LVDS} [get_ports {tx_data_out_n[4]}]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVDS} [get_ports {tx_data_out_p[5]}]
set_property -dict {PACKAGE_PIN C16 IOSTANDARD LVDS} [get_ports {tx_data_out_n[5]}]

set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVCMOS18} [get_ports enable]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS18} [get_ports txnrx]

set_property -dict {PACKAGE_PIN F12 IOSTANDARD LVCMOS18} [get_ports {gpio_status[0]}]
set_property -dict {PACKAGE_PIN E12 IOSTANDARD LVCMOS18} [get_ports {gpio_status[1]}]
set_property -dict {PACKAGE_PIN B10 IOSTANDARD LVCMOS18} [get_ports {gpio_status[2]}]
set_property -dict {PACKAGE_PIN A10 IOSTANDARD LVCMOS18} [get_ports {gpio_status[3]}]
set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS18} [get_ports {gpio_status[4]}]
set_property -dict {PACKAGE_PIN H12 IOSTANDARD LVCMOS18} [get_ports {gpio_status[5]}]
set_property -dict {PACKAGE_PIN B11 IOSTANDARD LVCMOS18} [get_ports {gpio_status[6]}]
set_property -dict {PACKAGE_PIN A11 IOSTANDARD LVCMOS18} [get_ports {gpio_status[7]}]

set_property -dict {PACKAGE_PIN B6 IOSTANDARD LVCMOS18} [get_ports {gpio_ctl[0]}]
set_property -dict {PACKAGE_PIN A6 IOSTANDARD LVCMOS18} [get_ports {gpio_ctl[1]}]
set_property -dict {PACKAGE_PIN C7 IOSTANDARD LVCMOS18} [get_ports {gpio_ctl[2]}]
set_property -dict {PACKAGE_PIN C6 IOSTANDARD LVCMOS18} [get_ports {gpio_ctl[3]}]

set_property -dict {PACKAGE_PIN D12 IOSTANDARD LVCMOS18} [get_ports gpio_en_agc]
set_property -dict {PACKAGE_PIN C11 IOSTANDARD LVCMOS18} [get_ports gpio_sync]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS18} [get_ports gpio_resetb]

set_property PACKAGE_PIN B9 [get_ports spi_csn]
set_property IOSTANDARD LVCMOS18 [get_ports spi_csn]
set_property PULLUP true [get_ports spi_csn]
set_property -dict {PACKAGE_PIN B8 IOSTANDARD LVCMOS18} [get_ports spi_clk]
set_property -dict {PACKAGE_PIN A8 IOSTANDARD LVCMOS18} [get_ports spi_mosi]
set_property -dict {PACKAGE_PIN A7 IOSTANDARD LVCMOS18} [get_ports spi_miso]

# clocks

create_clock -period 4.000 -name rx_clk [get_ports rx_clk_in_p]

